In [2]:
import pandas as pd

db = pd.read_csv('/Users/anacariane/Desktop/programaria/licitacoes.csv', sep=';', encoding='latin1')

db.columns

Index(['Número Licitação', 'Código UG', 'Nome UG', 'Código Modalidade Compra',
       'Modalidade Compra', 'Número Processo', 'Objeto', 'Situação Licitação',
       'Código Órgão Superior', 'Nome Órgão Superior', 'Código Órgão',
       'Nome Órgão', 'UF', 'Município', 'Data Resultado Compra',
       'Data Abertura', 'Valor Licitação'],
      dtype='object')

In [3]:
db[db["Situação Licitação"]=="Encerrado"]

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Data Abertura,Valor Licitação
3,12018,925135,BANCO CENTRAL DO BRASIL - RECIFE,6,Dispensa de Licitação,148097,"Objeto: TV LED de 65 polegadas, UHD 4k, com co...",Encerrado,20101,Sem informação,25201,BANCO CENTRAL DO BRASIL-ORC.FISCAL/SEG.SOCIAL,-3,Inválido,04/12/2018,30/11/2018,"11075,9900"
16,12018,130129,SUPERINT.REG.DE DESENV.DA LAV.CACAUEIRA/MT,6,Dispensa de Licitação,0000000000032018,Objeto: Atender despesas com telefonia fixa e ...,Encerrado,22000,Ministério da Agricultura e Pecuária,22000,Ministério da Agricultura e Pecuária - Unid,MT,ALTA FLORESTA,06/12/2018,NaN,"1541,7000"
18,12018,135097,EMBRAPA CAFE,7,Inexigibilidade de Licitação,21163.000694/2018,Objeto: Serviço de genotipagem de 384 amostras...,Encerrado,22000,Ministério da Agricultura e Pecuária,22202,Empresa Brasileira de Pesquisa Agropecuária,DF,BRASILIA,04/12/2018,NaN,"90504,0000"
19,12018,152140,IFB - CAMPUS TAGUATINGA NORTE,6,Dispensa de Licitação,23162004935201845,Objeto: Contratação de empesa especializada a ...,Encerrado,26000,Ministério da Educação,26428,Instituto Federal de Brasília,DF,BRASILIA,31/12/2018,NaN,"2068,0000"
24,12018,153092,BIBLIOTECA CENTRAL DA UFPE,6,Dispensa de Licitação,23076025958201862,Objeto: Aquisição de Equipamento de Proteção I...,Encerrado,26000,Ministério da Educação,26242,Universidade Federal de Pernambuco,PE,RECIFE,06/12/2018,29/11/2018,"5609,0000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15327,907662018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90766,"Objeto: Fornecimento de fogão, para entrega na...",Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,10/12/2018,04/12/2018,"817,2000"
15328,907732018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90773,Objeto: Prestação de serviços para locação de ...,Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,20/12/2018,05/12/2018,"8400,0000"
15329,908252018,926130,DIVISÃO DE CENTRO DE SERV COMPRATILHADOS BSB,6,Dispensa de Licitação,PL.CSG.A.90825,Objeto: Coleta e descarte de resíduos industri...,Encerrado,20101,Sem informação,91081,FURNAS-CENTRAIS ELETRICAS S.A.,-3,Inválido,21/12/2018,17/12/2018,"9040,0000"
15333,990922018,158139,"INST.FED.DE EDUC.,CIENC.E TEC.FLUMINENSE",6,Dispensa de Licitação,23317009092201862,Objeto: Aquisição de material para revisão do ...,Encerrado,26000,Ministério da Educação,26434,Instituto Federal Fluminense,RJ,CAMPOS DOS GOYTACAZES,03/12/2018,NaN,"1149,7500"
15334,996252018,153035,UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO,6,Dispensa de Licitação,23085000625201811,Objeto: Pagamento da taxa referente ao primeir...,Encerrado,26000,Ministério da Educação,26254,Universidade Federal do Triângulo Mineiro,MG,UBERABA,04/12/2018,NaN,"298,0000"

In [4]:
db["Situação Licitação"].value_counts()

Situação Licitação
Encerrado                         9016
Publicado                         3709
Evento de Resultado de Julgame    1922
Retificação                        127
Evento de Alteração Publicad        93
Evento de Suspensão Publicado       72
Anulação                            67
Revogação                           63
Divulgado                           55
Evento de Adiamento Publicado       46
Evento de Retificação Public        45
Evento de Revogação Publicad        40
Evento de Alteração de Resul        37
Evento de Anulação Publicado        18
Evento de Retificação Divulg         7
Inválido                             4
Evento de Habilitação Public         4
Evento de Alteração Divulgad         4
Evento de Reabertura de Prazo        4
Evento de Adiamento Divulgado        3
Name: count, dtype: int64

In [11]:
db["Situação Licitação"].nunique()

20

In [6]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número Licitação          15336 non-null  int64
 1   Código UG                 15336 non-null  int64
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  int64
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  int64
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  int64
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra     15336 non-null  object
 15  Data Abertura             4688 non-null   object
 16  Valor Licitação           15336 non-null  object
dtypes: int64(5), object(12)
memory usage: 2.0+ MB

In [12]:
db["Data Abertura"].isnull().value_counts()

Data Abertura
True     10648
False     4688
Name: count, dtype: int64

In [13]:
db.isnull().sum()

Número Licitação                0
Código UG                       0
Nome UG                         0
Código Modalidade Compra        0
Modalidade Compra               0
Número Processo                 0
Objeto                          0
Situação Licitação              0
Código Órgão Superior           0
Nome Órgão Superior             0
Código Órgão                    0
Nome Órgão                      0
UF                              0
Município                       0
Data Resultado Compra           0
Data Abertura               10648
Valor Licitação                 0
dtype: int64

In [14]:
db.groupby("Data Abertura").apply(lambda group: group.isnull().sum())

/var/folders/5_/6j8429dj47z_h611_0h64fc00000gn/T/ipykernel_122/249778902.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  db.groupby("Data Abertura").apply(lambda group: group.isnull().sum())

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Data Abertura,Valor Licitação
Data Abertura,,,,,,,,,,,,,,,,,
01/06/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
01/10/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
01/11/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
01/12/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
02/04/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31/01/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31/07/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31/08/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31/10/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31/12/2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
db["Data Abertura"].unique()

array(['17/08/2016', nan, '30/11/2018', '29/11/2018', '19/06/2018',
       '03/09/2018', '22/11/2018', '12/12/2018', '06/04/2018',
       '14/12/2018', '09/11/2018', '20/04/2018', '04/12/2018',
       '07/12/2018', '29/10/2018', '13/04/2018', '06/11/2018',
       '18/09/2018', '07/11/2018', '06/12/2018', '05/12/2018',
       '23/11/2018', '09/10/2018', '21/11/2018', '31/12/2018',
       '28/12/2018', '08/11/2018', '13/12/2018', '31/10/2018',
       '14/08/2018', '23/10/2017', '10/12/2018', '16/11/2018',
       '27/12/2018', '13/11/2018', '18/12/2018', '27/11/2018',
       '05/11/2018', '21/09/2018', '19/10/2018', '20/11/2018',
       '14/11/2018', '11/10/2018', '25/06/2018', '16/10/2018',
       '12/11/2018', '25/09/2018', '03/10/2018', '26/12/2018',
       '17/12/2018', '10/10/2018', '19/12/2018', '23/10/2018',
       '20/12/2018', '18/10/2018', '11/12/2018', '26/11/2018',
       '03/12/2018', '19/07/2016', '12/06/2017', '23/08/2018',
       '22/10/2018', '25/07/2018', '19/11/2018', '30/10/2018',
       '04/06/2018', '28/11/2018', '01/11/2018', '27/09/2018',
       '21/12/2018', '12/06/2018', '25/10/2018', '25/04/2018',
       '17/10/2018', '05/09/2018', '28/09/2018', '23/01/2018',
       '09/08/2018', '24/12/2018', '06/09/2018', '06/07/2018',
       '03/05/2018', '23/07/2018', '15/11/2018', '29/01/2018',
       '02/10/2018', '04/10/2018', '24/10/2018', '24/09/2018',
       '16/02/2018', '04/09/2018', '17/05/2018', '10/09/2018',
       '26/10/2018', '01/10/2018', '05/10/2018', '18/06/2018',
       '23/12/2018', '05/06/2018', '31/07/2018', '28/06/2018',
       '08/10/2018', '19/09/2018', '15/10/2018', '21/08/2018',
       '08/11/2017', '24/07/2018', '28/03/2018', '19/07/2018',
       '02/05/2018', '27/08/2018', '17/04/2018', '26/09/2018',
       '22/10/2014', '05/04/2018', '29/08/2018', '26/02/2018',
       '09/05/2018', '01/06/2018', '16/08/2018', '24/05/2018',
       '24/08/2018', '12/09/2018', '15/03/2018', '22/03/2018',
       '31/01/2018', '13/06/2018', '15/08/2018', '11/09/2018',
       '28/08/2018', '08/08/2018', '30/08/2018', '27/06/2018',
       '04/04/2018', '03/08/2018', '24/11/2018', '11/04/2018',
       '10/05/2018', '05/07/2018', '20/08/2018', '16/04/2018',
       '02/08/2018', '29/03/2017', '12/07/2018', '10/08/2018',
       '08/05/2018', '08/12/2018', '30/07/2018', '14/09/2018',
       '23/11/2017', '18/04/2017', '13/09/2018', '08/02/2018',
       '17/09/2018', '20/09/2018', '24/04/2018', '31/08/2018',
       '28/11/2017', '21/03/2018', '21/06/2018', '15/05/2018',
       '13/12/2017', '27/07/2018', '22/08/2018', '23/02/2018',
       '14/06/2017', '07/05/2018', '16/07/2018', '02/11/2018',
       '01/12/2018', '30/10/2017', '14/11/2017', '17/08/2018',
       '09/04/2018', '02/04/2018', '22/06/2018', '17/07/2018',
       '27/03/2018', '10/11/2018', '22/12/2018'], dtype=object)

In [16]:
db["Data Abertura"] = db["Data Abertura"].fillna('00/00/0000')

In [17]:
db.isnull().sum()

Número Licitação            0
Código UG                   0
Nome UG                     0
Código Modalidade Compra    0
Modalidade Compra           0
Número Processo             0
Objeto                      0
Situação Licitação          0
Código Órgão Superior       0
Nome Órgão Superior         0
Código Órgão                0
Nome Órgão                  0
UF                          0
Município                   0
Data Resultado Compra       0
Data Abertura               0
Valor Licitação             0
dtype: int64